# Generated by Django 5.2 on 2026-08-12 19:36

import django.db.models.deletion
import src.apps.questions.domain.values.questions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answermodel',
            options={'ordering': ['order_number'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'ordering': ['order_number'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterUniqueTogether(
            name='answermodel',
            unique_together={('question', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='questionmodel',
            unique_together={('questionnaire', 'order_number')},
        ),
        migrations.CreateModel(
            name='QuestionnaireCompletionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Уникальный идентификатор')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Пройден')], default=src.apps.questions.domain.values.questions.QuestionnaireStatus['in_progress'], verbose_name='Статус прохождения')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала прохождения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания прохождения')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_completions', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_completions', to='questions.questionnairemodel', verbose_name='Опросник')),
            ],
            options={
                'verbose_name': 'Информация о прохождении опроса',
                'verbose_name_plural': 'Информация о прохождении опросов',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Уникальный идентификатор')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='questions.questionmodel', verbose_name='Вопрос')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='questions.answermodel', verbose_name='Ответ')),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='questions.questionnairecompletionmodel', verbose_name='Информация о прохождении')),
            ],
            options={
                'verbose_name': 'Выбранный ответ на вопрос',
                'verbose_name_plural': 'Выбранные ответы на вопросы',
            },
        ),
    ]
